### ISSUE TITLE
Opening a new Tab at the front of the List

### ISSUE THREAD

**Issue by RickStrahl** [ButchersBoy/Dragablz#105]
I'm finding I'm struggling with the fact that Dragablz is not respecting the Items collection in respect to it's ordering of items. The `GetOrderedHeaders()` you added addressed the most important issue - thank you very much. 

Here are a couple of cases where this affects behavior I'm trying to implement and  and I don't know how make this work with the Dragablz:

1) Opening a new tab I want to open it at the front of the list
2) Selecting a tab I want to move that to the front of the list. 

Essentially list is always ordered with the latest items active. Previously with raw TabItems this worked just by using `Insert(0,tab)` and/or setting the `TabIndex`. 

How can I do this now? 

FWIW, I'm adding and manipulating tabs in code rather than XAML/Bindings.

**Comment by ButchersBoy** [comment]
Yep, Dragablz can't respect the order of the collection due to the nature of WPF. If Dragablz switched the collection order for you the visual item would be unloaded and recreated, interrupting the flow of the user's actions re-ordering tearing out etc...so with Dragablz things have to be done slightly differently...
 
So, there are helper methods to assist you "putting things together". Primarily: 
https://github.com/ButchersBoy/Dragablz/blob/master/Dragablz/TabablzControl.cs#L104 

```public static void Addltem(object item, object nearltem, AddLocationHint addLocationHint) ```

This is static so it will find the "nearltem" in any Window and using the "addLocationHint" you can add 
before/after that item. 

Also of note is the non-static:

```public void AddToSource(object item)```

This will add an item to a binding ItemsSource, or the TabItems, so you would probably call that first, get your first item in, and then subsequently use AddItem....

...I should probably get this stuff in the wiki when I get time...

**Comment by RickStrahl** [comment]
So I tried doing the following:

```csharp
            //TabControl.Items.Insert(0, tab);
            if (TabControl.Items.Count > 0)
                TabablzControl.AddItem(tab, TabControl.Items[0], AddLocationHint.First);
            else
                TabControl.AddToSource(tab);
```

(and a few other combinations of this using Items.Insert() etc)

and it fails with:

> Did not find precisely one instance of adjacentTo

At the point where this is called Items[] has one item in it and it looks like hte right items are being added and used as  ajacent object.

![tabaddfirst](https://cloud.githubusercontent.com/assets/1374013/15635887/8d714328-25a1-11e6-8ca9-826d24d7b118.png)

**Comment by ButchersBoy** [comment]
Might be cos you are using TabItems and not models/objects...I'll try and have a look in the next couple of days.

**Comment by ButchersBoy** [comment]
Fixing coming soon...

**Comment by ButchersBoy** [comment]
Think this was fixed, closing.

**Comment by RickStrahl** [comment]
Yes I was able to make that work with the latest release. Thank you...

![image](https://cloud.githubusercontent.com/assets/1374013/19720451/e60d7d02-9b09-11e6-9e4c-25be631b305f.png)
