### ISSUE TITLE
When a tab is torn out, content bindings' setter gets called infinitely

### ISSUE THREAD

**Issue by dasjestyr** [ButchersBoy/Dragablz#49]
Out of the box, I replaced my tab control, which uses an item template for the tabs and content template for each tab's content. Immediately, when I tear the tab out, I was able to see that each property that is being bound to a property on the view model had its setter called infinitely. This is a bigger problem because I have an event fire to do some work each time one of those properties change.

**Comment by ButchersBoy** [comment]
Hi, typically whenever these issues get reported it is because the tab has been put into an existing application, and a bit of rework needs to be done.  Can you stuck a break point in the binding (maybe use PropertyChangedCallback) to try and decipher where it's coming from?  If you can post a test project which illustrates the problem I can try and debug it.

**Comment by dasjestyr** [comment]
Hi, sorry for the delay, it's been a long week. So, the only thing in the project that touches the setter on these properties is the view, so I'm not sure how to look for the cause. What I'll do (probably tomorrow) is branch my project and drop in your tab control again and then I'll get you that copy. Thanks

**Comment by ButchersBoy** [comment]
Is this an issue still? If so, post a repo please.  Otherwise I'll close.

**Comment by dasjestyr** [comment]
It is. Sorry, I've been swamped. I will come back to this hopefully this weekend or next. I'll have to find it again and then I'll just point you at the repo and tell you exactly where it is.

**Comment by dasjestyr** [comment]
I gutted everything and rebuilt the UI and the problem seems to be gone. I don't know what the problem could have been.
