### ISSUE TITLE
Reordering Items when dragged?

### ISSUE THREAD

**Issue by picrap** [ButchersBoy/Dragablz#96]
Currently, when dragging items, their list order does not change (only their display position), so if they are bound to a source, the items order in the source does not change.
Is there a way to do this with the current version?
If not, is there a chance it will be possible one day?

**Comment by ButchersBoy** [comment]
In a nutshell, no.  You have to think slightly differently, and use the PositionMonitor to monitor the order, and do what you want with that.  Due to the nature of WPF binding, if items get swapped, then UI elements get removed/added, and the whole dragging process goes down the toilet.  It's the nature of dragging tabs and the WPF beast...

**Comment by picrap** [comment]
You made the point! I'll think differently (I needed the order to save layout, but I'll bind and use positions, which is also fine).
